

cloud:
    aws:
      credentials:
        access-key: AKIA2OJ2F52D3HO35TXF
        secret-key: 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
      region:
        static: us-east-1
      stack:
        auto: false


application:
  bucket:
    name: ziptube1


server:
  port: 8090


